language: python
python: 2.7
dist: trusty

addons:
  apt:
    packages:
      - vera++

virtualenv:
  system_site_packages: true

before_install:
  - pip install --upgrade pip setuptools wheel

install:
  - pip install flake8
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support

script:
  # Code quality check
  - flake8 --ignore F403,F405
  - support/run-vera.sh spynnaker_visualisers
  