language: python
python:
  - 2.7
  - 3.6
dist: trusty
cache: pip

install:
  - pip install -r requirements.txt
  - pip install flake8 pylint

script:
  # Code quality check
  - flake8 --ignore F403,F405
  - ( pylint spynnaker_visualisers; exit $(($? & 35)) )
