language: python
python:
  - 2.7
  - 3.6
dist: trusty
cache: pip

addons:
  apt:
    packages:
      - vera++

before_install:
  - pip install --upgrade pip setuptools wheel

install:
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - pip install -r requirements.txt
  - pip install flake8 pylint

script:
  # Code quality check
  - flake8 --ignore F403,F405 spynnaker_visualisers
  - ( pylint spynnaker_visualisers; exit $(($? & 35)) )
  - support/run-vera.sh spynnaker_visualisers
